# Generated by Django 4.2.1 on 2023-05-22 17:52

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book1', models.CharField(max_length=20)),
                ('issue_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=blog.models.expiry)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_book', to='blog.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_book_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
